CREATE DATABASE OrganizationDB
USE OrganizationDB

CREATE TABLE OFFICES(OFFICE int PRIMARY KEY,CITY varchar(20) NOT NULL,REGION varchar(20) NOT NULL,TARGET varchar(20) NOT NULL, SALES varchar(20) NOT NULL)

INSERT INTO OFFICES VALUES (1, 'Dhaka', 'Mirpur', 'Branch1', 'LED'),(2, 'Dhaka', 'Uttara', 'Branch2', 'IoT'),
						   (3, 'Savar', 'Chandra', 'Branch3', '	Generators'),(4, 'Gazipur','Konabari', 'Branch4','Motors')


CREATE TABLE SALESPERSON
(
EMPL_NUM int PRIMARY KEY,
NAME varchar(20) NOT NULL,
AGE int NOT NULL,
TITLE varchar(30) NULL,
OFFICE int FOREIGN KEY REFERENCES OFFICES(OFFICE),
HIRE_DATE date NOT NULL,
QUOTA varchar(20) NULL,
MANAGER_NUM varchar(20) NOT NULL
) 


INSERT INTO SALESPERSON VALUES (1, 'Karim', 18, 'S1', 1, '2018-11-21', 'No', '001'),
                               (2, 'Rahim', 30, 'S2', 1,'2020-03-29', 'Yes', '001'),
                               (3, 'Mehedi', 37,'S3', 2,'2020-10-16', 'No', '002'),
							   (4, 'Hasan', 32, 'S4', 3,'2020-03-29', 'Yes', '003'),
                               (5, 'Andrew Mckenzie', 29, 'S5', 3,'2019-10-16', 'No', '003')
							   (6, 'Rofiq', 25, 'S4', 4, '2020-04-05', 'Yes', '003'),
							   


CREATE TABLE PRODUCTS
(
PRODUCT_ID int IDENTITY(1,1),
MFR_ID int NOT NULL,
DESCRIPTION varchar(20) NOT NULL,
PRICE int NOT NULL,
PRIMARY KEY (PRODUCT_ID,MFR_ID)
)

INSERT INTO PRODUCTS VALUES (01, 'ABC', 1000),(01, 'CDE', 1200),(02, 'EFG', 1400),(02, 'GHI', 1600 )


CREATE TABLE CUSTOMERS
(
CUST_NUM int IDENTITY(1,1) PRIMARY KEY,
COMPANY varchar(20) NOT NULL,
EMPL_NUM int FOREIGN KEY REFERENCES SALESPERSON(EMPL_NUM),
CREDIT_LIMIT int NULL
) 

INSERT INTO CUSTOMERS VALUES ('AB', 1, 10000),('BC', 2, 12000), ('CD', 3, 14000), ('DE', 4, 10000), ('EF', 5, 10000)


CREATE TABLE ORDERS
(
ORDER_NUM int IDENTITY(1,1) PRIMARY KEY,
ORDER_DATE date NOT NULL,
EMPL_NUM int FOREIGN KEY REFERENCES SALESPERSON(EMPL_NUM),
CUST_NUM int FOREIGN KEY REFERENCES CUSTOMERS(CUST_NUM),
PRODUCT_ID int,
MFR_ID int NOT NULL, 
QUANTITY INT NOT NULL,
QUOTA varchar(20) NULL,
AMOUNT int NOT NULL,

FOREIGN KEY (PRODUCT_ID, MFR_ID) REFERENCES PRODUCTS (PRODUCT_ID, MFR_ID)
) 


INSERT INTO ORDERS VALUES ('2021-01-20', 1, 1, 1, 01, 30, 'No', 30000),('2021-01-21', 1, 1, 1, 01, 32, 'No', 32000),
                          ('2021-01-25', 2, 2, 2, 01, 15, 'No', 24000),('2021-02-20', 2, 2, 2, 01, 16, 'No', 19200),
                          ('2021-05-15', 3, 3, 3, 02, 10, 'No', 14000),('2021-05-17', 3, 3, 4, 02, 25, 'No', 40000),
						  ('2021-07-10', 4, 4, 1, 01, 16, 'No', 16000),('2021-08-11', 4, 5, 2, 01, 10, 'No', 12000),
					      ('2021-08-12', 5, 5, 1, 01, 20, 'No', 20000)
						  
						  

SELECT SALESPERSON.EMPL_NUM, SALESPERSON.NAME, OFFICES.CITY, OFFICES.REGION from SALESPERSON, OFFICES 
where SALESPERSON.OFFICE = OFFICES.OFFICE


SELECT CUSTOMERS.CUST_NUM ORDERS.QUANTITY from CUSTOMERS, ORDERS
where CUSTOMERS.CUST_NUM = ORDERS.CUST_NUM AND QUANTITY = (SELECT MAX(ORDERS.QUANTITY) from ORDERS)

select CUST_NUM, QUANTITY  from ORDERS where QUANTITY = (SELECT MAX(QUANTITY) from ORDERS)


SELECT OFFICE, COUNT(*) AS no_of_EMPL from SALESPERSON GROUP BY OFFICE

SELECT EMPL_NUM, AVG(AMOUNT) from ORDERS WHERE AMOUNT > 30000 GROUP BY EMPL_NUM 


SELECT SUM(AMOUNT) from ORDERS,SALESPERSON
WHERE ORDERS.EMPL_NUM = SALESPERSON.EMPL_NUM AND SALESPERSON.NAME = 'Andrew Mckenzie' 


SELECT  (PRICE+0.25*PRICE) AS Imposed_vat_Price from PRODUCTS

		
	
SELECT * from CUSTOMERS LEFT JOIN ORDERS ON ORDERS.CUST_NUM = CUSTOMERS.CUST_NUM
WHERE(ORDER_DATE BETWEEN '2021-01-20' AND '2021-05-15') OR PRODUCT_ID LIKE '%2' 

SELECT * from CUSTOMERS LEFT JOIN ORDERS ON ORDERS.CUST_NUM = CUSTOMERS.CUST_NUM
WHERE(ORDER_DATE BETWEEN '2021-01-20' AND '2021-05-15')

SELECT CUSTOMERS.CUST_NUM, CUSTOMERS.COMPANY from CUSTOMERS LEFT JOIN ORDERS
ON ORDERS.CUST_NUM = CUSTOMERS.CUST_NUM
WHERE(ORDER_DATE BETWEEN '2021-01-20' AND '2021-05-15') 


SELECT SALESPERSON.NAME, OFFICES.CITY from SALESPERSON, OFFICES, ORDERS
WHERE SALESPERSON.OFFICE = OFFICES.OFFICE AND SALESPERSON.EMPL_NUM = ORDERS.EMPL_NUM

	   
SELECT E1.NAME AS ENAME, E2.NAME AS MNAME from SALESPERSON E1 INNER JOIN SALESPERSON E2 
ON E1.EMPL_NUM = E2.EMPL_NUM