--CEILING() function
SELECT CEILING(25.75)
SELECT CEILING(Salary) FROM CUSTOMER

--FLOOR() function
SELECT FLOOR(25.75)
SELECT FLOOR(Salary) FROM CUSTOMER

--SUM() function
SELECT SUM(Salary) FROM CUSTOMER

--AVG() function
SELECT AVG(Age) FROM CUSTOMER

--ROUND() function
SELECT ROUND(235.415, 2)
SELECT ROUND(235.417, 2, 0)

--POWER() function
SELECT POWER(4, 2)

--SQUARE() function
SELECT SQUARE(6)

--SQRT() function
SELECT SQRT(64)

--PI() Function
SELECT PI()

--LOG() Function
SELECT LOG(2)
SELECT LOG(4, 2)

--RADIANS() Function
SELECT RADIANS(180)