--Current database system date and time
SELECT GETDATE()
SELECT SYSDATETIME()

SELECT DAY('2017/08/25')
SELECT CONVERT (TIME, CURRENT_TIMESTAMP) 

--DATEADD() Function
SELECT DATEADD(YEAR,3,'1992-04-07') As IncrementYear
SELECT DATEADD(YEAR,3,GETDATE())

SELECT DATEADD(MONTH,2,DOB) As IncrementMonth FROM EMPLOYEE WHERE EmployeeID = 2

--DATEDIFF() Function
SELECT DATEDIFF(YEAR,'1992-03-11','1995-08-23') AS DateDiff

SELECT DATEPART(DAY,'2001-07-24') AS Day
SELECT DATEPART(DAY,DOB) As Day FROM EMPLOYEE WHERE EmployeeID = 2

SELECT DAY('1990-06-14') AS Day

SELECT DAY(DOB) AS Day FROM EMPLOYEE